# Generated by Django 3.2.9 on 2021-11-13 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_counter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foods',
            name='date',
            field=models.DateTimeField(default='November 12'),
        ),
    ]
