# Generated by Django 3.2.9 on 2021-11-13 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_counter', '0002_alter_foods_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foods',
            name='date',
        ),
    ]
