# Generated by Django 3.2.9 on 2021-11-13 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_counter', '0003_remove_foods_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='foods',
            name='foodType',
            field=models.CharField(default='100', max_length=5),
        ),
        migrations.AddField(
            model_name='foods',
            name='meal',
            field=models.CharField(default='100', max_length=5),
        ),
    ]
