# Generated by Django 3.2.9 on 2021-11-13 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_counter', '0004_auto_20211113_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foods',
            name='foodType',
        ),
        migrations.RemoveField(
            model_name='foods',
            name='meal',
        ),
    ]
